#config_version=5

mode:
  start_events: start_gym6_event
  restart_on_next_ball: true
  stop_events: stop_gym6_event 
  events_when_started:
  events_when_stopped:
  priority: 211 

slides:
  slide_mode_gym6_started:
    widgets:
      - type: text
        text: GYM 6
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 60
        x: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: GYM (gym6_gym)/3
        number_grouping: true
        min_digits: 2
        font_size: 50
        anchor_x: left
        anchor_y: bottom
        y: 10
        x: 10
  
slide_player:
  mode_gym6_started:
    slide_mode_gym6_started:
      target: middle   



variable_player:
  s_gym_active:
    gym6_gym: 1

event_player:
  check_gym6_gym{current_player.gym6_gym >= 3}:
    - stop_gym6_event


  s_gym_active:
    check_gym6_gym
