#config_version=5

mode:
  start_events: stop_gym1_event
  restart_on_next_ball: true
  stop_events: start_gym2_event
  events_when_started:
  events_when_stopped:
  priority: 202

event_player:
  s_gym_active:
    start_gym2_event
    
slides:
  slide_mode_gym1_ended_started:
    widgets:
      - type: text
        text: HIT GYM SHOT TO START GYM BATTLE
        font_size: 70
        y: 60
        x: 10
        anchor_x: left
        anchor_y: bottom
     
   
slide_player:
  mode_gym1_ended_started:
    slide_mode_gym1_ended_started:
      target: middle   