#config_version=5

mode:
  start_events: start_gym1_event
  restart_on_next_ball: true
  stop_events: stop_gym1_event 
  events_when_started:
  events_when_stopped:
  priority: 201

slides:
  slide_mode_gym1_started:
    widgets:
      - type: text
        text: GYM 1
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 60
        x: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: POP BUMPERS (gym1_pop)/9
        number_grouping: true
        min_digits: 2
        font_size: 50
        anchor_x: left
        anchor_y: bottom
        y: 10
        x: 10
  
slide_player:
  mode_gym1_started:
    slide_mode_gym1_started:
      target: middle   



variable_player:
  s_pop_right_active:
    gym1_pop: 1
    
  s_pop_top_active:
    gym1_pop: 1
    
  s_pop_bottom_active:
    gym1_pop: 1
    
event_player:
  check_gym1_pop{current_player.gym1_pop >= 9}:
    - stop_gym1_event

  
  s_pop_right_active:
    check_gym1_pop
    
  s_pop_top_active:
    check_gym1_pop
    
  s_pop_bottom_active:
    check_gym1_pop
