#config_version=5

#playfield_active for ball save, not ball_starting

hardware:
  platform: fast
  driverboards: fast


fast:
  ports: com4, com5


#hardware:
# platform: smart_virtual

#virtual_platform_start_active_switches:
#  - s_trough

config:
  - player_variables.yaml
  - key_mapping.yaml

modes:
  - base
  - pichu
  - evolve_pichu
  - pikachu
  - evolve_pikachu
  - raichu
  - gym0
  - gym1
  - gym1_ended
  - gym2
  - gym2_ended
  - gym3
  - gym3_ended
  - gym4
  - gym4_ended
  - gym5
  - gym5_ended
  - gym6
  - gym6_ended
  - gym7
  - gym7_ended
  - gym8
  - gym8_ended
  - score_display
  - attract
  - high_score
  
window:
  width: 1280
  height: 720
  resizable: false
  fullscreen: false
  borderless: true
  exit_on_escape: true

displays:
  window:
    width: 1280
    height: 720
  top:
    width: 1280
    height: 260
  middle:
    width: 1280
    height: 260
  bottom:
    width: 1280
    height: 100

slides:
  layout_3_mini:
    background_color: red
    widgets:
      - type: display
        width: 1280
        height: 300
        x: 0
        y: 430
        anchor_x: left
        anchor_y: bottom
        source_display: top
      - type: display
        width: 1280
        height: 300
        x: 0
        y: 120
        anchor_x: left
        anchor_y: bottom
        source_display: middle
      - type: display
        width: 1280
        height: 100
        x: 0
        y: 0
        anchor_x: left
        anchor_y: bottom
        source_display: bottom
      
  welcome_slide:
    widgets:
      - type: text
        text: LOADING...
        font_size: 50
        color: red

widget_styles:
    attract_mode_high_score_display_label:
        font_size: 30
        anchor_x: right
        anchor_y: top
        x: center-10
        bold: true
    attract_mode_high_score_display_name:
        font_size: 30
        anchor_x: right
        anchor_y: top
        x: center+70
    attract_mode_high_score_display_score:
        font_size: 30
        anchor_x: left
        anchor_y: top
        x: center+90
        number_grouping: true
        min_digits: 1

# attract_started:
#   widgets:
#      - text: ATTRACT MODE
#        type: text
 

slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started

  game_started:
    layout_3_mini:
      target: window

game:
  balls_per_game: 3
  allow_start_with_loose_balls: true

keyboard:
  s:
    switch: s_start
  t:
    switch: s_trough
  1:
    event: start_gym1

switches:
  s_flipper_right:
    number: 0-1
    tags: flipper_right
  s_flipper_left:
    number: 0-0
    tags: flipper_left
  s_start:
    number: 0-2
    tags: start
  #s_:
    #number: 0-3
  #s_:
    #number: 0-4
  #s_:
    #number: 0-5
  #s_:
    #number: 0-6
  #s_:
    #number: 0-7
  s_drop_left:
    number: 1-0
    tags:
  s_drop_center:
    number: 1-1
    tags:
  s_drop_right:
    number: 1-2
    tags:
  s_plunger_lane:
    number: 1-3
  s_saucer:
    number: 1-4
    platform_settings:
      debounce_open: 5
      debounce_close: 250
    #ignore_window_ms: 1000
    #debounce_ms: 1000
  s_pop_right:
    number: 1-5
#    tags: playfield_active
    ignore_window_ms: 250
  s_pop_top:
    number: 1-6
#    tags: playfield_active
    ignore_window_ms: 250
  s_pop_bottom:
    number: 1-7
#    tags: playfield_active
    ignore_window_ms: 250
  s_drain:
    number: 1-8
  s_trough:
    number: 1-9
  s_sling_right:
    number: 1-10
    tags:
  s_sling_left:
    number: 1-11
    tags:
  s_gym:
    number: 1-12
    tags: playfield_active
    ignore_window_ms: 1000
  s_spinner:
    number: 1-13
    tags: playfield_active
  #s_
    #number: 1-14
  #s_
    #number: 1-15

coils:
  c_drain:
    number: 1-0
    default_pulse_ms: 20
  c_trough:
    number: 1-1
    default_pulse_ms: 7
    debug: true
  c_flipper_right :
    number: 1-2
    allow_enable: yes
    default_pulse_ms: 15
    default_hold_power: .25
  c_flipper_left:
    number: 1-3
    allow_enable: yes
    default_pulse_ms: 15
    default_hold_power: .25
  c_sling_right:
    number: 1-4
    default_pulse_ms: 60
  c_sling_left:
    number: 1-5
    default_pulse_ms: 60
  c_saucer:
    number: 1-6
    default_pulse_ms: 60
  c_pop_right:
    number: 1-8
    default_pulse_ms: 80
  c_pop_bottom:
    number: 1-9
    default_pulse_ms: 80
  c_pop_top:
    number: 1-10
    default_pulse_ms: 80
  c_drop_reset:
    number: 1-11
    default_pulse_ms: 400

flippers:
  flipper_left:
    main_coil: c_flipper_left
    activation_switch: s_flipper_left
    #enable_events: machine_reset_phase_3
  flipper_right:
    main_coil: c_flipper_right
    activation_switch: s_flipper_right
    #enable_events: machine_reset_phase_3

autofire_coils:
  slingshot_left:
    coil: c_sling_left
    switch: s_sling_left
  slingshot_right:
    coil: c_sling_right
    switch: s_sling_right
  pop_top:
    coil: c_pop_top
    switch: s_pop_top
  pop_bottom:
    coil: c_pop_bottom
    switch: s_pop_bottom
  pop_right:
    coil: c_pop_right
    switch: s_pop_right

drop_targets:
    drop1:
        debug: false
        switch: s_drop_left
    drop2:
        debug: false
        switch: s_drop_center
    drop3:
        debug: false
        switch: s_drop_right

drop_target_banks:
    right_bank:
        debug: false
        drop_targets: drop1, drop2, drop3
        reset_coils: c_drop_reset
        reset_events: ball_starting, machine_reset_phase_3
        reset_on_complete: 1s

ball_devices:
  bd_drain:
    ball_switches: s_drain
    eject_coil: c_drain
    eject_targets: bd_trough
    tags: drain

  bd_trough:
    ball_switches: s_trough
    eject_coil: c_trough
    eject_targets: bd_plunger
    tags: home, trough
    debug: true

  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true

  bd_saucer:
    ball_switches: s_saucer
    eject_coil: c_saucer
    eject_timeouts: 1s

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default
    
#machine_vars:
#  last_game_num_players:
#    value_type: int
#    persist: true
