#config_version=5

mode:
  start_events: start_gym5_event
  restart_on_next_ball: true
  stop_events: stop_gym5_event 
  events_when_started:
  events_when_stopped:
  priority: 209 

slides:
  slide_mode_gym5_started:
    widgets:
      - type: text
        text: GYM 5
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 60
        x: 10
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: DROP TARGETS (gym5_drop_targets)/9
        number_grouping: true
        min_digits: 2
        font_size: 50
        anchor_x: left
        anchor_y: bottom
        y: 10
        x: 10
  
slide_player:
  mode_gym5_started:
    slide_mode_gym5_started:
      target: middle   



variable_player:
  s_drop_left_active:
    gym5_drop_targets: 1
    
  s_drop_center_active:
    gym5_drop_targets: 1
    
  s_drop_right_active:
    gym5_drop_targets: 1

event_player:
  check_gym5_drop_targets{current_player.gym5_drop_targets >= 9}:
    - stop_gym5_event
 
    
  s_drop_left_active:
    check_gym5_drop_targets
    
  s_drop_center_active:
    check_gym5_drop_targets
    
  s_drop_right_active:
    check_gym5_drop_targets